### PR TITLE
Fix example in README

### PR DESCRIPTION
**Pull request by RReverser**

### CODE REVIEW

**Comment by Yamakaky** [comment]
Good! In fact, can you use Bindings::write? It would be more appropriate.

**Comment by RReverser** [comment]
Do you mean with intermediate buffer and so on? Feels like that would unnecessarily complicate the example.

**Comment by RReverser** [comment]
Ah no, you mean `.write(file)`?

**Comment by Yamakaky** [comment]
Yes, `bindings.write(file)`

**Comment by RReverser** [comment]
That doesn't work unless we box `File`. Is it really necessary?

**Comment by Yamakaky** [comment]
Hum, OK!

**Pull request merged**
